# Generated by Django 6.0.5 on 2026-06-03 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('hr_round', 'HR Round'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
